Fraud Detection

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

In [2]:
df = pd.read_csv('creditcard.csv')
df

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
284802,172786.0,-11.881118,10.071785,-9.834783,-2.066656,-5.364473,-2.606837,-4.918215,7.305334,1.914428,...,0.213454,0.111864,1.014480,-0.509348,1.436807,0.250034,0.943651,0.823731,0.77,0
284803,172787.0,-0.732789,-0.055080,2.035030,-0.738589,0.868229,1.058415,0.024330,0.294869,0.584800,...,0.214205,0.924384,0.012463,-1.016226,-0.606624,-0.395255,0.068472,-0.053527,24.79,0
284804,172788.0,1.919565,-0.301254,-3.249640,-0.557828,2.630515,3.031260,-0.296827,0.708417,0.432454,...,0.232045,0.578229,-0.037501,0.640134,0.265745,-0.087371,0.004455,-0.026561,67.88,0
284805,172788.0,-0.240440,0.530483,0.702510,0.689799,-0.377961,0.623708,-0.686180,0.679145,0.392087,...,0.265245,0.800049,-0.163298,0.123205,-0.569159,0.546668,0.108821,0.104533,10.00,0
284806,172792.0,-0.533413,-0.189733,0.703337,-0.506271,-0.012546,-0.649617,1.577006,-0.414650,0.486180,...,0.261057,0.643078,0.376777,0.008797,-0.473649,-0.818267,-0.002415,0.013649,217.00,0

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     284807 non-null  float64
 22  V22     284807 non-null  float64
 23  V23     284807 non-null  float64
 24  V24     284807 non-null  float64
 25  V25     284807 non-null  float64
 26  V26     284807 non-null  float64
 27  V27     284807 non-null  float64
 28  V28     284807 non-null  float64
 29  Amount  284807 non-null  float64
 30  Class   284807 non-null  int64
dtypes: float64(30), int64(1)
memory usage: 67.4 MB

In [4]:
df.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [5]:
# no null values

## EDA

In [6]:
import ydata_profiling
from ydata_profiling import ProfileReport

c:\Users\Harshit\AppData\Local\Programs\Python\Python310\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [62]:
#profile = ProfileReport(df, explorative=True,dark_mode=True)
#profile.to_file('fraud_detection.html')

In [8]:
df['Class'].value_counts()

0    284315
1       492
Name: Class, dtype: int64

In [9]:
# the data is highly unbalanced, therefore we are seperating both the classes
fraud = df[df['Class']==1]
norm = df[df['Class']==0]

In [10]:
norm.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [11]:
fraud.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
541,406.0,-2.312227,1.951992,-1.609851,3.997906,-0.522188,-1.426545,-2.537387,1.391657,-2.770089,...,0.517232,-0.035049,-0.465211,0.320198,0.044519,0.177840,0.261145,-0.143276,0.00,1
623,472.0,-3.043541,-3.157307,1.088463,2.288644,1.359805,-1.064823,0.325574,-0.067794,-0.270953,...,0.661696,0.435477,1.375966,-0.293803,0.279798,-0.145362,-0.252773,0.035764,529.00,1
4920,4462.0,-2.303350,1.759247,-0.359745,2.330243,-0.821628,-0.075788,0.562320,-0.399147,-0.238253,...,-0.294166,-0.932391,0.172726,-0.087330,-0.156114,-0.542628,0.039566,-0.153029,239.93,1
6108,6986.0,-4.397974,1.358367,-2.592844,2.679787,-1.128131,-1.706536,-3.496197,-0.248778,-0.247768,...,0.573574,0.176968,-0.436207,-0.053502,0.252405,-0.657488,-0.827136,0.849573,59.00,1
6329,7519.0,1.234235,3.019740,-4.304597,4.732795,3.624201,-1.357746,1.713445,-0.496358,-1.282858,...,-0.379068,-0.704181,-0.656805,-1.632653,1.488901,0.566797,-0.010016,0.146793,1.00,1

In [12]:
norm.Amount.describe()

count    284315.000000
mean         88.291022
std         250.105092
min           0.000000
25%           5.650000
50%          22.000000
75%          77.050000
max       25691.160000
Name: Amount, dtype: float64

In [13]:
fraud.Amount.describe()
# the mean of fraud data is little more compared to normal data
# and same with max data 
# and fraud is very less

count     492.000000
mean      122.211321
std       256.683288
min         0.000000
25%         1.000000
50%         9.250000
75%       105.890000
max      2125.870000
Name: Amount, dtype: float64

For training our data we will try to balace the data and take equal values for both normal and fraud data

In [14]:
df.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,94838.202258,0.008258,-0.006271,0.012171,-0.007860,0.005453,0.002419,0.009637,-0.000987,0.004467,...,-0.000644,-0.001235,-0.000024,0.000070,0.000182,-0.000072,-0.000089,-0.000295,-0.000131,88.291022
1,80746.806911,-4.771948,3.623778,-7.033281,4.542029,-3.151225,-1.397737,-5.568731,0.570636,-2.581123,...,0.372319,0.713588,0.014049,-0.040308,-0.105130,0.041449,0.051648,0.170575,0.075667,122.211321

In [15]:
normal = norm.sample(n=492)
normal.head()
# normal data is divided randomly having 492 samples

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
218405,141303.0,-1.440104,0.551020,-0.572547,-0.791662,1.276755,-0.379215,1.039349,-0.428402,0.451564,...,-0.439806,-0.556372,0.496505,0.057101,-0.267664,0.048938,-0.937787,-0.239246,14.93,0
68514,53028.0,-3.611048,2.800348,0.621131,-2.312789,0.047393,-0.506789,1.240798,-0.613650,3.455719,...,-0.800940,-0.321544,-0.055807,-0.304473,0.225405,0.671549,0.640440,-0.324688,7.61,0
98276,66592.0,1.592518,-0.819425,-0.382846,-1.445899,-0.915860,-1.081680,-0.472090,-0.376919,-2.121297,...,-0.207543,-0.207967,-0.141041,-0.124392,0.737414,-0.051213,-0.005804,0.001090,15.00,0
9618,14437.0,1.242271,-0.177529,0.360619,-0.108596,-0.075899,0.614240,-0.687806,0.196390,1.654188,...,-0.071705,0.025669,-0.134315,-1.137918,0.237475,1.117602,-0.082709,-0.020941,15.95,0
123302,76877.0,-1.171733,0.268942,0.505258,0.306230,0.953351,-0.268608,0.070576,0.281278,-0.670348,...,-0.140022,-0.608709,-0.049578,-0.867317,-0.611558,0.098378,-0.305408,-0.139514,17.99,0

In [16]:
new_data = pd.concat([normal, fraud], axis=0)
new_data.shape

(984, 31)

In [17]:
# comparing the value of now data to the old one and both are approximately same
new_data.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,93228.953252,-0.220320,-0.124050,-0.037278,-0.019419,0.170211,-0.036983,-0.053057,-0.132864,0.001433,...,-0.018701,0.011995,-0.004456,0.070019,0.026791,0.028032,0.023852,-0.021296,-0.020128,89.802744
1,80746.806911,-4.771948,3.623778,-7.033281,4.542029,-3.151225,-1.397737,-5.568731,0.570636,-2.581123,...,0.372319,0.713588,0.014049,-0.040308,-0.105130,0.041449,0.051648,0.170575,0.075667,122.211321

In [18]:
# now splitting the data into target and features
X = new_data.drop(columns='Class')
y = new_data['Class']

In [32]:
X.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
218405,141303.0,-1.440104,0.551020,-0.572547,-0.791662,1.276755,-0.379215,1.039349,-0.428402,0.451564,...,-0.433886,-0.439806,-0.556372,0.496505,0.057101,-0.267664,0.048938,-0.937787,-0.239246,14.93
68514,53028.0,-3.611048,2.800348,0.621131,-2.312789,0.047393,-0.506789,1.240798,-0.613650,3.455719,...,2.019463,-0.800940,-0.321544,-0.055807,-0.304473,0.225405,0.671549,0.640440,-0.324688,7.61
98276,66592.0,1.592518,-0.819425,-0.382846,-1.445899,-0.915860,-1.081680,-0.472090,-0.376919,-2.121297,...,-0.344004,-0.207543,-0.207967,-0.141041,-0.124392,0.737414,-0.051213,-0.005804,0.001090,15.00
9618,14437.0,1.242271,-0.177529,0.360619,-0.108596,-0.075899,0.614240,-0.687806,0.196390,1.654188,...,-0.106302,-0.071705,0.025669,-0.134315,-1.137918,0.237475,1.117602,-0.082709,-0.020941,15.95
123302,76877.0,-1.171733,0.268942,0.505258,0.306230,0.953351,-0.268608,0.070576,0.281278,-0.670348,...,0.191278,-0.140022,-0.608709,-0.049578,-0.867317,-0.611558,0.098378,-0.305408,-0.139514,17.99

In [20]:
y

218405    0
68514     0
98276     0
9618      0
123302    0
         ..
279863    1
280143    1
280149    1
281144    1
281674    1
Name: Class, Length: 984, dtype: int64

In [21]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
X, y, test_size=0.2,stratify=y ,random_state=2)

In [22]:
print(X.shape, X_train.shape, X_test.shape)

(984, 30) (787, 30) (197, 30)

In [23]:
print(y.shape, y_train.shape, y_test.shape)

(984,) (787,) (197,)

In [24]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()

In [25]:
lr.fit(X_train,y_train)

c:\Users\Harshit\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

# Checking Accuracy

In [26]:
from sklearn.metrics import accuracy_score

In [27]:
X_train_pred = lr.predict(X_train)
training_data_accuracy = accuracy_score(X_train_pred,y_train)
print('accuracy of training data is : ',training_data_accuracy)

accuracy of training data is :  0.9466327827191868

In [28]:
X_test_pred = lr.predict(X_test)
testing_data_accuracy = accuracy_score(X_test_pred,y_test)
print('accuracy of testing data is : ',testing_data_accuracy)

accuracy of testing data is :  0.9086294416243654

In [41]:
X_test

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
247995,153761.0,1.146259,1.403458,-4.159148,2.660107,-0.323217,-1.836071,-1.623740,0.259562,-1.132044,...,0.284831,0.564450,0.445744,-0.141136,-0.265517,0.362260,-0.416062,0.507370,0.243744,51.37
171551,120694.0,2.038957,-0.143189,-1.253255,0.195396,0.130755,-0.616247,0.074871,-0.154049,0.327566,...,-0.189150,-0.265565,-0.685627,0.263691,-0.494823,-0.270722,0.207535,-0.077137,-0.073887,8.99
99374,67089.0,1.176533,-0.201858,1.230043,0.869122,-1.132178,-0.310200,-0.653104,0.099359,1.001157,...,-0.124829,-0.095911,-0.110632,0.034296,0.415947,0.238520,0.318004,0.013354,0.026733,11.50
183852,125979.0,-0.032440,0.844725,0.654853,-0.379124,-0.018628,-1.562349,0.982111,-0.214898,-0.045564,...,-0.097758,-0.200688,-0.417976,0.190915,0.853813,-0.635432,0.089979,0.248770,0.105106,2.69
15451,26833.0,-20.532751,12.373989,-23.009003,6.144821,-15.587296,-4.384491,-15.939003,13.696416,-3.948455,...,1.592754,1.754608,-1.466115,-0.856779,0.125777,1.402587,-0.223755,1.574249,0.469201,99.99
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
108258,70828.0,0.196707,1.189757,0.704882,2.891388,0.045555,1.245730,-1.198714,-2.421616,-1.232089,...,0.646616,-1.328132,0.189311,-0.005524,-0.814708,0.400924,0.286281,0.135215,0.257315,0.76
12108,21046.0,-16.917468,9.669900,-23.736443,11.824990,-9.830548,-2.514829,-17.290657,1.820408,-6.264903,...,0.996745,-2.336111,0.972755,1.241866,-1.051086,0.038009,0.672317,2.108471,-1.421243,1.00
99506,67150.0,-1.824295,0.403327,-1.994122,2.756558,-3.139064,0.408185,-1.209045,1.095634,-1.447225,...,1.503688,0.838760,0.341727,0.947506,-0.145493,0.049326,0.831065,0.332421,0.252713,489.71
74496,55614.0,-7.347955,2.397041,-7.572356,5.177819,-2.854838,-1.795239,-8.783235,0.437157,-3.740598,...,0.073164,-0.175273,0.543325,-0.547955,-0.503722,-0.310933,-0.163986,1.197895,0.378187,0.83
251594,155411.0,-0.562267,-0.199555,-0.769539,-2.050035,0.628363,-1.397397,2.786319,-0.953523,-1.997120,...,-0.027602,0.109859,0.598031,0.099492,0.044978,0.452318,0.724925,-0.228664,-0.076988,254.99

Applying Decision Tree

In [48]:
from sklearn import tree
model = tree.DecisionTreeClassifier(criterion="entropy")
model.fit(X_train,y_train)

DecisionTreeClassifier(criterion='entropy')

In [49]:
model.score(X_train,y_train)

1.0

In [50]:
model.score(X_test,y_test)
# here the accuracy is approx 86%

0.9137055837563451

In [51]:
print(df.iloc[218405])

Time      141303.000000
V1            -1.440104
V2             0.551020
V3            -0.572547
V4            -0.791662
V5             1.276755
V6            -0.379215
V7             1.039349
V8            -0.428402
V9             0.451564
V10            0.477575
V11           -1.302302
V12            0.415560
V13            1.364567
V14           -0.548857
V15           -0.275020
V16            0.063999
V17           -0.895715
V18           -0.684275
V19            0.320273
V20           -0.433886
V21           -0.439806
V22           -0.556372
V23            0.496505
V24            0.057101
V25           -0.267664
V26            0.048938
V27           -0.937787
V28           -0.239246
Amount        14.930000
Class          0.000000
Name: 218405, dtype: float64

In [52]:
# we tested it on a random data
model.predict([[141303.0,-1.440104,0.551020,-0.572547,-0.791662,1.276755,-0.379215,1.039349,-0.428402,0.451564,0.477575,-0.302302,0.415560,1.364567,-0.548857,-0.275020,0.603999,-0.895715,-0.684275,0.320273,-0.433886,-0.439806,-0.556372,0.496505,0.057101,-0.267664,0.048938,-0.937787,-0.239246,14.93]])

c:\Users\Harshit\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array([0], dtype=int64)

In [ ]:
model.predict([[141303.0,-1.440104,0.551020,-0.572547,-0.791662,1.276755,-0.379215,1.039349,-0.428402,0.451564,0.477575,-0.302302,0.415560,1.364567,-0.548857,-0.275020,0.603999,-0.895715,-0.684275,0.320273,-0.433886,-0.439806,-0.556372,0.496505,0.057101,-0.267664,0.048938,-0.937787,-0.239246,14.93]])